language: python
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y telnet
install:
- pip install tox
script:
- tox
deploy:
  provider: pypi
  user: kstaniek
  password:
    secure: lZnumViwbaDRBWJbVujdr3ejuNki4i2P2+WsMQq8bksj7i+AJiza60UC2Z35t/Hu05dZ/o2FxgE8aBy/FjGzT+BNDI8QxYCGiBIDjNcdPNGhcFNGeY95Yyug7QuCirzBZYYwN56oK//RkEftJxb06lmxwF26w6yskzAAGaVr6aOHEi4rGk2+8W5SPS9U/GM6BeE0Q75JbWaJEV6YhheeUBvDlYZm69KF4tJ8zy1B/QJ1iRoCZb1HISlWJpw0XGkWiJ4IM9O5/EXsMFQDvsPEfYb5hBmtqfknl1pK6GeQzaYWI/WwoJTRLeWnuTbrk3+XWtmwPoPnQBWVP8C+JFi5voGkPbBxAUJvebDnQwW9GZ0uJLU98U1JIYjJ7R0HnJo1zfeOb0hqGkcf2OI5NEI/gtSAiUc/MV5IYtalprDRNS2Dicbz8a/D6TLu24XrATDTLN3c1dt2beSknZXd6NNhBQQz7qb4BZOA/eZBsKhixAG0p+k8fBtfxfU5bOylLdlFtV05qRB0qHqRka6UolpHj01UUrahIyWZYyrJxW6qovQhCmY+m4kJjsnElCXMibQvtGuFe5FLA+Sfm1YqZuhvRCKnQ35Ua2F6Boa86+PAO+qOYss3YW2Sr3taxOttOjg9n7mxzw7qK+enTKnaPZ9s3ni+ePkrXk6MviJscMb20gE=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: kstaniek/condoor
  skip_upload_docs: true
